# fly.toml app configuration file generated for adjourn-pocketbase on 2025-11-22T10:45:51+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adjourn-pocketbase'
primary_region = 'syd'

[build]

[[mounts]]
  source = 'pb_data'
  destination = '/pb/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
